package com.gate.mockexam.pipeline.domain;

import jakarta.persistence.*;
import lombok.*;
import java.math.BigDecimal;

/**
 * Payload for METADATA artifact type.
 * Generated by Worker 1 (MetadataGeneratorWorker).
 */
@Entity
@Table(name = "ai_metadata_details")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AiMetadataDetails {

    @Id
    @Column(name = "artifact_id", length = 100)
    private String artifactId;

    @OneToOne(fetch = FetchType.LAZY)
    @MapsId
    @JoinColumn(name = "artifact_id")
    private AiArtifact artifact;

    @Column(nullable = false, length = 150)
    private String subject;

    @Column(nullable = false, length = 150)
    private String topic;

    @Column(length = 150)
    private String subtopic;

    /** EASY, MEDIUM, HARD */
    @Column(length = 50)
    private String difficulty;

    /** Bloom's Taxonomy: Remember, Understand, Apply, Analyze, Evaluate, Create */
    @Column(name = "blooms_level", length = 50)
    private String bloomsLevel;

    /** Estimated solving time in seconds */
    @Column(name = "estimated_time")
    private Integer estimatedTime;

    @Column(precision = 3, scale = 2)
    private BigDecimal confidence;
}
