package com.gate.mockexam.pipeline.domain;

import jakarta.persistence.*;
import lombok.*;

/**
 * Payload for EXPLANATION artifact type.
 * Generated by Worker 2 (ExplanationGeneratorWorker).
 */
@Entity
@Table(name = "explanation_details")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ExplanationDetails {

    @Id
    @Column(name = "artifact_id", length = 100)
    private String artifactId;

    @OneToOne(fetch = FetchType.LAZY)
    @MapsId
    @JoinColumn(name = "artifact_id")
    private AiArtifact artifact;

    @Column(name = "explanation_text", columnDefinition = "TEXT", nullable = false)
    private String explanationText;

    /** Confirmed correct answer after AI cross-validation */
    @Column(name = "final_answer", columnDefinition = "TEXT")
    private String finalAnswer;

    /** Alternative approach to solving the question */
    @Column(name = "alt_approach", columnDefinition = "TEXT")
    private String altApproach;
}
