package com.gate.mockexam.pipeline.domain;

import jakarta.persistence.*;
import lombok.*;

/** Payload for HINT artifact type. Generated by Worker 4 (HintGeneratorWorker). */
@Entity
@Table(name = "hint_details")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class HintDetails {

    @Id
    @Column(name = "artifact_id", length = 100)
    private String artifactId;

    @OneToOne(fetch = FetchType.LAZY)
    @MapsId
    @JoinColumn(name = "artifact_id")
    private AiArtifact artifact;

    @Column(name = "hint_text", columnDefinition = "TEXT", nullable = false)
    private String hintText;

    /** 1=nudge, 2=directional, 3=near-answer */
    @Column(name = "complexity_level", nullable = false)
    @Builder.Default
    private Integer complexityLevel = 1;
}
